### ISSUE TITLE
Configuration params

### ISSUE THREAD

**Issue by matancor99** [VIS4ROB-lab/ccm_slam#11]
Hey,
What are the #T_SC matrix parameters stand for?
They do not exist in the method of calibration I use, not in the original orb slam implementation.

**Comment by patriksc** [comment]
Hi, T_SC is the transformation from **C**amera frame to **S**ensor frame (i.e. the IMU frame). It's used to transform the estimated trajectory into the IMU frame before writing it into a file, since we're usually evaluating on the EuRoC dataset, and the EuRoC ground-truth is expressed in the IMU frame. The algorithm itself does not need the IMU frame, you can set it to identity if you don't need it.

**Comment by patriksc** [comment]
Closed - inactive
