### ISSUE TITLE
tracking is often lost  after loopfind?

### ISSUE THREAD

**Issue by pengcheng730** [VIS4ROB-lab/ccm_slam#22]

**Comment by manthan99** [comment]
@pengcheng730 happens to me sometimes when the GBA is taking place. It seems that a lack of computation is causing this since I am running simultaneously 2 agents. Thus when map merging is taking place, the tracking gets lost. You may try reducing the playback speed of bag files which might solve the issue

**Comment by manthan99** [comment]
You may check this out
#9

**Comment by patriksc** [comment]
Closed - inactive
