### ISSUE TITLE
Static Transform parameters

### ISSUE THREAD

**Issue by DanielRoeder1** [VIS4ROB-lab/ccm_slam#42]
I am trying to understand the values used in the static transformers to adjust them to my own case.

From https://github.com/VIS4ROB-lab/ccm_slam/issues/21 I understand that the roll is set deliberately higher (2 > 1.571) to account for a slightly downward-facing camera. But why is the yaw and roll in general rotated by 90deg?

In the "Using your own Data" section example of the readme, such a rotation is left out. So I would interpret that I would mainly need to account for the camera angle (roll) when using my own data?

**Comment by patriksc** [comment]
Hello Daniel
Generally, the static transform does not have any influence on the SLAM estimate. We have chosen the values such that we found it most convenient to examine the SLAM map in RVIZ. You can use the transform as is, set it to identity, or change the values so that you find it convenient to observe the estimate for your camera setup.
