### ISSUE TITLE
run on the kitti dataset

### ISSUE THREAD

**Issue by ghost** [VIS4ROB-lab/ccm_slam#5]
Hi, when I ran this code on the kitti dataset, it always failed to initialize. And I had adjust conf/vi_euroc.yaml correctly.

**Comment by patriksc** [comment]
We ran a brief test on KITTI (sequences 00,01,02,03). The motion pattern of the car is not optimal for monocular system such as CCM-SLAM, since it is mostly movement in the camera axis, causing problems with initialization and drift. We converted the single image files to a rosbag files for our tests. On seq. 00, CCM-SLAM initializes for us. We also tried to with down-sampled images (factor 0.5), and with this data, also seq. 02 and 03 initialize after approx. 23 and 15 sec respectively, this seems to alleviate the initialization problems.

**Comment by SiuKeungm** [comment]
> We ran a brief test on KITTI (sequences 00,01,02,03). The motion pattern of the car is not optimal for monocular system such as CCM-SLAM, since it is mostly movement in the camera axis, causing problems with initialization and drift. We converted the single image files to a rosbag files for our tests. On seq. 00, CCM-SLAM initializes for us. We also tried to with down-sampled images (factor 0.5), and with this data, also seq. 02 and 03 initialize after approx. 23 and 15 sec respectively, this seems to alleviate the initialization problems.

**Comment by soulslicer** [comment]
@patriksc How do you run it on the KITTI dataset? How did you convert the single image files into rosbag files. What topics are required for ccmslam? Can you provide some KITTI bag examples?

**Comment by patriksc** [comment]
Unfortunately, the bagfiles are quite large, so we cannot provide them here. However, converting images to a bagfile is quite straightforward, you can for example use or take inspiration from these tools:

https://github.com/ethz-asl/kitti_to_rosbag
https://github.com/raulmur/BagFromImages

Maybe you want to make some to the code adjustments, for example to change the resolution of the images.
