### ISSUE TITLE
Loadmap error！

### ISSUE THREAD

**Issue by sun1f** [VIS4ROB-lab/ccm_slam#58]
Hi, I am so impressed with this amazing cslam project. 

I got a little question here: 
Aftering successfully saving maps by using rosservice command, I set the parameter `LoadMap` in `Server.launch` to true in order to load maps, jsut following the guidance of `README`. But something went wrong, is there anything else I should do when loading maps?

Hope to receive your reply！
![bd7b9d5030ff740d46d6e369e720ed4](https://user-images.githubusercontent.com/88525849/217214290-39cb7538-bc8f-4a4c-a70d-e189a39b7e20.png)

**Comment by patriksc** [comment]
Hi, thanks for your message. It looks like something has gone wrong here, the map you are trying to load contains a landmark with an ID not known to the map. Could be a glitch in the function that saved the map. Did you try this with multiple maps, and the error is reproducible over multiple saved/loaded maps? Or did it just happen for a single map? 

For this specific map, you could try changing the code to just skip this landmark in the loop and continue with the next one, instead of directly exiting. if it's only a single landmark with this error, the map might still work. But generally, stored maps should be able to be loaded again.

**Comment by patriksc** [comment]
Closed - inactive
