### ISSUE TITLE
error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by TwiceMao** [VIS4ROB-lab/ccm_slam#62]
I meet this error，how could I solve it？

[ccmslam/ccmslamClientNode1-2] process has died [pid 999291, exit code -6, cmd /media/zrr/B6DC2D32DC2CEE75/maomao/ccmslam_ws/devel/lib/ccmslam/ccmslamClientNode /media/zrr/B6DC2D32DC2CEE75/maomao/ccmslam_ws/src/ccm_slam/cslam/conf/ORBvoc.txt /media/zrr/B6DC2D32DC2CEE75/maomao/ccmslam_ws/src/ccm_slam/cslam/conf/replica_vi_euroc.yaml __name:=ccmslamClientNode1 __log:=/home/zrr/.ros/log/991423c8-f2e8-11ed-b628-ed28cb613320/ccmslam-ccmslamClientNode1-2.log].
log file: /home/zrr/.ros/log/991423c8-f2e8-11ed-b628-ed28cb613320/ccmslam-ccmslamClientNode1-2*.log

![1684132677111](https://github.com/VIS4ROB-lab/ccm_slam/assets/43490149/0d0e987b-c4bc-4768-a321-36c46821556f)
![1684132716207](https://github.com/VIS4ROB-lab/ccm_slam/assets/43490149/1d92c703-587b-48dc-8271-d805c8697487)

**Comment by patriksc** [comment]
Hi! According to the error message, you are using OpenCV 4. We have only tested CCM-SLAM with OpenCV 2 and 3, and since the error comes from an OpenCV call, that's very likely the root cause here. I would recommend to link against OpenCV 3, that should solve the problem. 

Alternatively, you could look into the debug information with gbd, and try to fix the problem locally s that it works with OpenCV 4. 

I would also recommend to double-check with `ldd` that the CCM-SLAM executable does not link against 2 OpenCV versions (e.g. 3.x and 4.x) - this can happen if you have e.g. a system wide version of OpenCV and one in the workspace. This needs to be resolved then, because it causes CCM-SLAM to crash.

**Comment by patriksc** [comment]
Closed - inactive
